stages:
  prepare:
    cmd: python prepare.py
    deps:
    - data/census.csv
    - prepare.py
    outs:
    - data/clean_census.csv
    - model/labelbinarizer.pkl
  segregate:
    cmd: python segregate.py
    deps:
    - data/clean_census.csv
    outs:
    - data/test.csv
    - data/train.csv
  train:
    cmd: python train.py
    deps:
    - data/train.csv
    - train.py
    outs:
    - model/model.pkl
    - model/used_columns.pkl
