data:
  raw:
    name: census.csv
    columns:
      workclass: [Private, Self-emp-not-inc, Self-emp-inc,Federal-gov, Local-gov, State-gov, Without-pay, Never-worked]
      education: [Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool]
      marital_status: [Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse]
      occupation: [Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces]
      relationship: [Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried]
      race: [White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black]
      sex: [Female, Male]
      native_country: [United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands]
      salary: ["<=50K", ">50K"]
  clean:
    name: clean_census.csv
    test_size: 0.2
    random_state: 42
    stratify: salary
model:
  features:
    categorical: [workclass, education, marital_status, occupation, relationship, race, sex, native_country]
    numerical: [age, fnlgt, hours_per_week]
  target: salary
  random_forest:
    n_estimators: 1000
    criterion: 'gini'
    max_depth: 13
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 10
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: true
    oob_score: false
    n_jobs: null
    random_state: 42
    verbose: 0
    warm_start: false
    class_weight: "balanced"
    ccp_alpha: 0.0
    max_samples: null
metrics:
  fbeta_score:
    beta: 1
    zero_division: 1
  precision_score:
    zero_division: 1
  recall_score:
    zero_division: 1


